root = "/var/lib/buildkit"

[grpc]
address = ["tcp://0.0.0.0:8372", "unix:///run/buildkit/buildkitd.sock"]


# [grpc.tls]
# cert = "/etc/buildkit/tls.crt"
# key = "/etc/buildkit/tls.key"
# ca = "/etc/buildkit/tlsca.crt"

[worker.oci]
enabled = true
gckeepstorage = 30000000000
snapshotter = "stargz"
max-parallelism = 4  # Adjust based on CPU and memory resources
max-concurrency = 16  # Adjust based on I/O capabilities

[worker.oci.stargzSnapshotter]
max-concurrency = 16  # Adjust based on I/O capabilities
chunk_size = 25000000  # Keep chunk size to balance I/O
no_background_fetch = true
noprefetch = true
no_prometheus = true

[[worker.oci.gcpolicy]]
all = true
keepDuration = "24h"  # Less frequent GC to reduce CPU load
keepBytes = 50000000000  # Increased storage to avoid frequent GC

[gc]
  [gc.policy]
    all = true
    keepDuration = "24h"
    keepBytes = 50000000000

[registry.configs."https://index.docker.io/v1/"]
  auth = "{{DOCKER_AUTH}}"

[system]
  platformsCacheMaxAge = "1h"
