root = "/var/lib/buildkit"

[grpc]
address = ["tcp://0.0.0.0:8372", "unix:///run/buildkit/buildkitd.sock"]

# [grpc.tls]
# cert = "/etc/buildkit/tls.crt"
# key = "/etc/buildkit/tls.key"
# ca = "/etc/buildkit/tlsca.crt"

[worker.oci]
enabled = true
snapshotter = "overlayfs"
max-parallelism = 4

[worker.oci.stargzSnapshotter]
no_background_fetch = true
noprefetch = true
no_prometheus = true
max_concurrency = 8

[worker.oci.stargzSnapshotter.blob]
chunk_size = 25000000

[[worker.oci.gcpolicy]]
keepBytes = 30000000000

[gc]
  [gc.policy]
    all = true
    keepDuration = "12h"
    keepBytes = 30000000000

[registry.configs."https://index.docker.io/v1/"]
  auth = "{{DOCKER_AUTH}}"
