root = "/var/lib/buildkit"

[grpc]
address = ["tcp://0.0.0.0:8372", "unix:///run/buildkit/buildkitd.sock"]

# [grpc.tls]
# cert = "/etc/buildkit/tls.crt"
# key = "/etc/buildkit/tls.key"
# ca = "/etc/buildkit/tlsca.crt"

[worker.oci]
enabled = true
gckeepstorage = 30000000000
cniPoolSize = 16
snapshotter = "stargz"  # Or "stargz" based on testing
max-parallelism = 4  # Adjust based on CPU and memory resources
max-concurrency = 16  # Adjust based on I/O capabilities

[worker.oci.stargzSnapshotter]
max_concurrency = 16
chunk_size = 25000000  # Adjust based on I/O performance
no_background_fetch = true
noprefetch = true
no_prometheus = true

[[worker.oci.gcpolicy]]
all = true
keepDuration = "12h"  # Adjust based on retention needs and storage capacity
keepBytes = 30000000000  # Adjust based on available storage and build artifact sizes

[gc]
  [gc.policy]
    all = true
    keepDuration = "12h"
    keepBytes = 30000000000

[registry.configs."https://index.docker.io/v1/"]
  auth = "{{DOCKER_AUTH}}"


[system]
  # how often buildkit scans for changes in the supported emulated platforms
  platformsCacheMaxAge = "1h"