name: CI
on: push

permissions:
  contents: read
  id-token: write
  packages: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    if: github.repository != ''
    strategy:
      fail-fast: false
      matrix:
        include:
          - project: builder-buildkit
          - project: builder-circleci
    steps:
      - uses: actions/checkout@v3
      - uses: docker/metadata-action@v4
        id: meta
        with:
          images: ghcr.io/depot/${{ matrix.project }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
      - name: Build and Push Docker image
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker build -t ghcr.io/${{ github.repository }}/${{ matrix.project }} .
          docker push ghcr.io/${{ github.repository }}/${{ matrix.project }}